name: validate

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze --fatal-infos
      - name: Test
        run: dart test
      - name: Validate widgets
        run: dart run bin/fa_widgets.dart validate --root widgets
